# Generated by Django 5.0.1 on 2024-03-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="paystack_ref",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
