# Generated by Django 4.1 on 2023-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product/image/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
